// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamBG.Infrastructure.Data;

#nullable disable

namespace StreamBG.Infrastructure.Migrations
{
    [DbContext(typeof(StreamBGDbContext))]
    [Migration("20260523185306_SeedSubscriptionAndDonationData")]
    partial class SeedSubscriptionAndDonationData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StreamBG.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStreamer")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "seed-streamer-1",
                            Bio = "📺 Тестов стриймър акаунт за демонстрация",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "streamer@example.com",
                            IsAdmin = false,
                            IsBanned = false,
                            IsStreamer = true,
                            PasswordHash = "SEED_ACCOUNT_NOT_FOR_LOGIN",
                            Username = "teststreamer"
                        },
                        new
                        {
                            Id = "seed-donor-1",
                            Bio = "💰 Тестов донор акаунт за демонстрация",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "donor@example.com",
                            IsAdmin = false,
                            IsBanned = false,
                            IsStreamer = false,
                            PasswordHash = "SEED_ACCOUNT_NOT_FOR_LOGIN",
                            Username = "testdonor"
                        });
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("#6441a5");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#6441a5",
                            Icon = "🎮",
                            Name = "Игри",
                            Slug = "igri",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#e91e63",
                            Icon = "🎵",
                            Name = "Музика",
                            Slug = "muzika",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = "#ff5722",
                            Icon = "🎨",
                            Name = "Изкуство",
                            Slug = "izkustvo",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Color = "#4caf50",
                            Icon = "⚽",
                            Name = "Спорт",
                            Slug = "sport",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "#2196f3",
                            Icon = "📚",
                            Name = "Образование",
                            Slug = "obrazovanie",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Color = "#00bcd4",
                            Icon = "💻",
                            Name = "Технологии",
                            Slug = "tehnologii",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Color = "#ff9800",
                            Icon = "🍳",
                            Name = "Готвене",
                            Slug = "gotvene",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Color = "#795548",
                            Icon = "✈️",
                            Name = "Пътешествия",
                            Slug = "puteshestvia",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            Color = "#9c27b0",
                            Icon = "🎭",
                            Name = "Забавление",
                            Slug = "zabavlenie",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            Color = "#607d8b",
                            Icon = "🔮",
                            Name = "Друго",
                            Slug = "drugo",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("StreamBG.Core.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StreamId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StreamId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Clip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<double>("OffsetSeconds")
                        .HasColumnType("float");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceStreamId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceVodId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StreamerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("StreamerUserId");

                    b.ToTable("Clips");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.DeviceToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonorDisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonorUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmojiAnimation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalPaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShownInChat")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PaymentProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StreamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DonorUserId");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10.00m,
                            CompletedAt = new DateTime(2026, 6, 1, 18, 30, 5, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 6, 1, 18, 30, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "BGN",
                            DonorDisplayName = "testdonor",
                            DonorUserId = "seed-donor-1",
                            EmojiAnimation = "🎉",
                            IsAnonymous = false,
                            IsShownInChat = true,
                            Message = "Stratoten strim! Produlzhavai taka!",
                            RecipientUserId = "seed-streamer-1",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 5.50m,
                            CompletedAt = new DateTime(2026, 6, 2, 20, 15, 3, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 6, 2, 20, 15, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "BGN",
                            DonorDisplayName = "Anonimen fen",
                            IsAnonymous = true,
                            IsShownInChat = true,
                            Message = "❤️",
                            RecipientUserId = "seed-streamer-1",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 25.00m,
                            CompletedAt = new DateTime(2026, 6, 5, 19, 0, 4, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 6, 5, 19, 0, 0, 0, DateTimeKind.Utc),
                            CurrencyCode = "BGN",
                            DonorDisplayName = "testdonor",
                            DonorUserId = "seed-donor-1",
                            EmojiAnimation = "🏆",
                            IsAnonymous = false,
                            IsShownInChat = true,
                            Message = "Za strima na godinata!",
                            RecipientUserId = "seed-streamer-1",
                            Status = 1
                        });
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Follow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FollowedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FolloweeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FollowerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FolloweeId");

                    b.HasIndex("FollowerId", "FolloweeId")
                        .IsUnique();

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SentCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.NotificationPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DonationReceived")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("bit");

                    b.Property<bool>("NewSubscriber")
                        .HasColumnType("bit");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("bit");

                    b.Property<bool>("StreamStarted")
                        .HasColumnType("bit");

                    b.Property<bool>("SubscriptionRenewal")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("NotificationPreferences");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Stream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacebookStreamKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLive")
                        .HasColumnType("bit");

                    b.Property<bool>("RelayToFacebook")
                        .HasColumnType("bit");

                    b.Property<bool>("RelayToTikTok")
                        .HasColumnType("bit");

                    b.Property<bool>("RelayToYouTube")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreamKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TikTokStreamKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ViewerCount")
                        .HasColumnType("int");

                    b.Property<string>("YouTubeStreamKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StreamKey")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.StreamAnalytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("PeakViewers")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StreamId")
                        .HasColumnType("int");

                    b.Property<int>("TotalChatMessages")
                        .HasColumnType("int");

                    b.Property<int>("TotalUniqueViewers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StreamAnalytics");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.SubscriptionPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalPaymentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserSubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserSubscriptionId");

                    b.ToTable("SubscriptionPayments");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BadgeEmoji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Perks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceMonthly")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeColor = "#FFD700",
                            BadgeEmoji = "⭐",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = "seed-streamer-1",
                            CurrencyCode = "BGN",
                            Description = "Базов абонамент на месечна база — емотикони и реклами намалени",
                            IsActive = true,
                            Name = "Месечен",
                            Perks = "[\"\\u0427\\u0430\\u0442 \\u0435\\u043C\\u043E\\u0442\\u0438\\u043A\\u043E\\u043D\\u0438\",\"\\u0411\\u0435\\u0437 \\u0440\\u0435\\u043A\\u043B\\u0430\\u043C\\u0438\"]",
                            PriceMonthly = 4.99m
                        },
                        new
                        {
                            Id = 2,
                            BadgeColor = "#9B59B6",
                            BadgeEmoji = "👑",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorUserId = "seed-streamer-1",
                            CurrencyCode = "BGN",
                            Description = "Годишен абонамент с 2 безплатни месеца — VIP бейдж, ексклузивен чат, приоритетен стрийм",
                            IsActive = true,
                            Name = "Годишен",
                            Perks = "[\"\\u0427\\u0430\\u0442 \\u0435\\u043C\\u043E\\u0442\\u0438\\u043A\\u043E\\u043D\\u0438\",\"\\u0411\\u0435\\u0437 \\u0440\\u0435\\u043A\\u043B\\u0430\\u043C\\u0438\",\"\\u0415\\u043A\\u0441\\u043A\\u043B\\u0443\\u0437\\u0438\\u0432\\u0435\\u043D \\u0447\\u0430\\u0442\",\"VIP \\u0431\\u0435\\u0439\\u0434\\u0436\",\"\\u041F\\u0440\\u0438\\u043E\\u0440\\u0438\\u0442\\u0435\\u0442\\u0435\\u043D \\u0441\\u0442\\u0440\\u0438\\u0439\\u043C\"]",
                            PriceMonthly = 49.99m
                        });
                });

            modelBuilder.Entity("StreamBG.Core.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RenewsAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubscriberUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("SubscriberUserId", "PlanId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodChapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Timestamp")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VodVideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VodVideoId");

                    b.ToTable("VodChapters");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("Timestamp")
                        .HasColumnType("time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VodVideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VodVideoId");

                    b.ToTable("VodComments");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessedFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceStreamId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StorageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("VodVideos");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.WatchProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("Position")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VodVideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "VodVideoId")
                        .IsUnique();

                    b.ToTable("WatchProgress");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.ChatMessage", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.Stream", "Stream")
                        .WithMany("ChatMessages")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Clip", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "Streamer")
                        .WithMany()
                        .HasForeignKey("StreamerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Streamer");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.DeviceToken", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Donation", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "DonorUser")
                        .WithMany()
                        .HasForeignKey("DonorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "RecipientUser")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonorUser");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Follow", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "Followee")
                        .WithMany("Followers")
                        .HasForeignKey("FolloweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Followee");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.NotificationPreference", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Stream", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.Category", "CategoryRef")
                        .WithMany("Streams")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "User")
                        .WithMany("Streams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryRef");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.SubscriptionPayment", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.UserSubscription", "UserSubscription")
                        .WithMany("Payments")
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.SubscriptionPlan", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatorUser");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.UserSubscription", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.SubscriptionPlan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "SubscriberUser")
                        .WithMany()
                        .HasForeignKey("SubscriberUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("SubscriberUser");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodChapter", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.VodVideo", "VodVideo")
                        .WithMany("Chapters")
                        .HasForeignKey("VodVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VodVideo");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodComment", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.VodVideo", "VodVideo")
                        .WithMany("Comments")
                        .HasForeignKey("VodVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VodVideo");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodVideo", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Streams");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Category", b =>
                {
                    b.Navigation("Streams");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Stream", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.UserSubscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodVideo", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
