// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StreamBG.Infrastructure.Data;

#nullable disable

namespace StreamBG.Infrastructure.Migrations
{
    [DbContext(typeof(StreamBGDbContext))]
    [Migration("20260522075345_AddCategoriesAndSearch")]
    partial class AddCategoriesAndSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StreamBG.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStreamer")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("#6441a5");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#6441a5",
                            Icon = "🎮",
                            Name = "Игри",
                            Slug = "igri",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#e91e63",
                            Icon = "🎵",
                            Name = "Музика",
                            Slug = "muzika",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = "#ff5722",
                            Icon = "🎨",
                            Name = "Изкуство",
                            Slug = "izkustvo",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Color = "#4caf50",
                            Icon = "⚽",
                            Name = "Спорт",
                            Slug = "sport",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "#2196f3",
                            Icon = "📚",
                            Name = "Образование",
                            Slug = "obrazovanie",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Color = "#00bcd4",
                            Icon = "💻",
                            Name = "Технологии",
                            Slug = "tehnologii",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Color = "#ff9800",
                            Icon = "🍳",
                            Name = "Готвене",
                            Slug = "gotvene",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Color = "#795548",
                            Icon = "✈️",
                            Name = "Пътешествия",
                            Slug = "puteshestvia",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            Color = "#9c27b0",
                            Icon = "🎭",
                            Name = "Забавление",
                            Slug = "zabavlenie",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            Color = "#607d8b",
                            Icon = "🔮",
                            Name = "Друго",
                            Slug = "drugo",
                            SortOrder = 10
                        });
                });

            modelBuilder.Entity("StreamBG.Core.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StreamId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StreamId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Follow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FollowedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FolloweeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FollowerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FolloweeId");

                    b.HasIndex("FollowerId", "FolloweeId")
                        .IsUnique();

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Stream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacebookStreamKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLive")
                        .HasColumnType("bit");

                    b.Property<bool>("RelayToFacebook")
                        .HasColumnType("bit");

                    b.Property<bool>("RelayToTikTok")
                        .HasColumnType("bit");

                    b.Property<bool>("RelayToYouTube")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StreamKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TikTokStreamKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ViewerCount")
                        .HasColumnType("int");

                    b.Property<string>("YouTubeStreamKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StreamKey")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Streams");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.StreamAnalytics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("PeakViewers")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StreamId")
                        .HasColumnType("int");

                    b.Property<int>("TotalChatMessages")
                        .HasColumnType("int");

                    b.Property<int>("TotalUniqueViewers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StreamAnalytics");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodChapter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Timestamp")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VodVideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VodVideoId");

                    b.ToTable("VodChapters");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("Timestamp")
                        .HasColumnType("time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VodVideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VodVideoId");

                    b.ToTable("VodComments");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessedFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceStreamId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StorageKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("VodVideos");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.WatchProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("Position")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VodVideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "VodVideoId")
                        .IsUnique();

                    b.ToTable("WatchProgress");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.ChatMessage", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.Stream", "Stream")
                        .WithMany("ChatMessages")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Follow", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "Followee")
                        .WithMany("Followers")
                        .HasForeignKey("FolloweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Followee");

                    b.Navigation("Follower");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Stream", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.Category", "CategoryRef")
                        .WithMany("Streams")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "User")
                        .WithMany("Streams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryRef");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodChapter", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.VodVideo", "VodVideo")
                        .WithMany("Chapters")
                        .HasForeignKey("VodVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VodVideo");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodComment", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.VodVideo", "VodVideo")
                        .WithMany("Comments")
                        .HasForeignKey("VodVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VodVideo");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodVideo", b =>
                {
                    b.HasOne("StreamBG.Core.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Following");

                    b.Navigation("Streams");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Category", b =>
                {
                    b.Navigation("Streams");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.Stream", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("StreamBG.Core.Entities.VodVideo", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
